[package]
name = "curlywas"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmparser = "0.81"
wasm-encoder = "0.8"
anyhow = "1"
chumsky = "0.5"
ariadne = "0.1"
pico-args = "0.4"
